# Generated by Django 3.0 on 2021-05-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nthsocialmediaapp', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='nthsocialmediaapp.Comments'),
        ),
    ]
